import time
start_time = time.time()

import gzip
def ncd(string1, string2):
    Cx1 = len(gzip.compress(string1.encode()))
    Cx2 = len(gzip.compress(string2.encode()))
    combined_str = " ".join([string1, string2])
    Cx1x2 = len(gzip.compress(combined_str.encode()))

    # Calculate NCD
    ncd = (Cx1x2 - min(Cx1, Cx2)) / max(Cx1, Cx2)
    similarity = 1 - ncd
    dissimilarity = ncd
    return similarity, dissimilarity
string1 = [
    "Mission Impossible One Movie",
    "Mission: Impossible I Film",
    "Movie - Mission Impossible 1",
    "MI 1 Movie",
    "Impossible Mission 1 Film",
    "Mission: Impossible First Movie",
    "MI1 Film",
    "Mission Impossible Episode 1 Movie",
    "First Mission Impossible Film",
    "Movie Mission Impossible One",
    "Mission Impossible: The First Movie",
    "Impossible Mission 1 Motion Picture",
    "MI One Film",
    "Mission Impossible I Flick",
    "Movie Mission Impossible Episode 1",
    "Mission: Impossible - The First Film",
    "MI 1 Motion Picture",
    "Mission Impossible 1st Movie",
    "Mission Impossible: Episode One",
    "Film - Mission Impossible I",
    "MI One Motion Picture",
    "Mission Impossible First Installment",
    "Mission Impossible: Part 1",
    "Mission Impossible Film Number One",
    "MI Episode 1 Movie",
    "Impossible Mission Episode 1 Film",
    "Movie Mission: Impossible One",
    "MI - The First Movie",
    "Mission Impossible One Flick",
    "Mission Impossible: Initial Movie",
    "Impossible Mission One Film",
    "Movie MI 1",
    "Mission Impossible 1st Installment",
    "Mission: Impossible One Flick",
    "MI One Flick",
    "Mission Impossible: The Initial Movie",
    "First Mission Impossible Motion Picture",
    "Movie Mission Impossible: 1",
    "MI 1 Flick",
    "Mission Impossible 1st Motion Picture",
    "Mission Impossible: Episode 1 Film",
    "MI: The First Movie",
    "Mission Impossible: The Beginning Movie",
    "Mission Impossible One Picture",
    "Movie Mission Impossible - 1",
    "Mission Impossible: The Premiere Film",
    "MI One Picture",
    "Mission Impossible 1st Flick",
    "Mission Impossible: The Debut Movie",
    "MI Episode One Movie",
    "Movie - MI 1",
    "Mission Impossible: Part One",
    "Mission Impossible Episode 1 Flick",
    "MI: The Beginning Movie",
    "Mission Impossible 1 Premiere",
    "Movie Mission Impossible: First",
    "Mission Impossible: The Introductory Movie",
    "MI One Premiere",
    "Mission Impossible: The First Picture",
    "Mission Impossible 1st Premiere",
    "Movie Mission: Impossible - 1",
    "MI Episode 1 Flick",
    "Mission Impossible: The Opening Movie",
    "Mission Impossible One Premiere",
    "Mission Impossible: First Episode",
    "MI: The Premiere Movie",
    "Mission Impossible 1st Episode",
    "Movie MI: 1",
    "Mission Impossible",
    "Mission Impossible: The Commencement Movie",
    "Mission Impossible One Opening",
    "MI: Episode 1",
    "Movie - MI Episode 1",
    "Mission Impossible: The First Episode",
    "Mission Impossible One Commencement",
    "MI Episode 1 Premiere",
    "Movie Mission Impossible: Episode 1",
    "Mission Impossible: The First Installment",
    "Mission Impossible One Commencement Movie",
    "MI 1 Commencement",
    "Movie MI: Episode One",
    "Mission Impossible: The First Part",
    "Mission Impossible One Beginning",
    "MI Episode One Premiere",
    "Movie Mission Impossible: The First",
    "Mission Impossible: First Commencement",
    "Mission Impossible One Commencement Flick",
    "MI: Episode 1 Movie",
    "Movie - MI Episode One",
    "Mission Impossible: The Initial Episode",
    "Mission Impossible One Commencement Film",
    "MI 1 Commencement Movie",
    "Movie MI: Episode 1",
    "Mission Impossible: The First Part Movie",
    "Mission Impossible One Beginning Film",
    "MI Episode One Commencement",
    "Movie Mission Impossible: The Premiere",
    "Mission Impossible: First Commencement Movie",
    "Mission Impossible One Commencement Picture",
    "MI: Episode One Premiere",
    "Movie - Mission Impossible One",
    "Mission: Impossible I Film",
    "Movie - Mission Impossible 1",
    "MI 1 Movie",
    "Impossible Mission 1 Film",
    "Mission: Impossible First Movie",
    "MI1 Film",
    "Mission Impossible Episode 1 Movie",
    "First Mission Impossible Film",
    "Movie Mission Impossible One",
    "Mission Impossible: The First Movie",
    "Impossible Mission 1 Motion Picture",
    "MI One Film",
    "Mission Impossible I Flick",
    "Movie Mission Impossible Episode 1",
    "Mission: Impossible - The First Film",
    "MI 1 Motion Picture",
    "Mission Impossible 1st Movie",
    "Mission Impossible: Episode One",
    "Film - Mission Impossible I",
    "MI One Motion Picture",
    "Mission Impossible First Installment",
    "Mission Impossible: Part 1",
    "Mission Impossible Film Number One",
    "MI Episode 1 Movie",
    "Impossible Mission Episode 1 Film",
    "Movie Mission: Impossible One",
    "MI - The First Movie",
    "Mission Impossible One Flick",
    "Mission Impossible: Initial Movie",
    "Impossible Mission One Film",
    "Movie MI 1",
    "Mission Impossible 1st Installment",
    "Mission: Impossible One Flick",
    "MI One Flick",
    "Mission Impossible: The Initial Movie",
    "First Mission Impossible Motion Picture",
    "Movie Mission Impossible: 1",
    "MI 1 Flick",
    "Mission Impossible 1st Motion Picture",
    "Mission Impossible: Episode 1 Film",
    "MI: The First Movie",
    "Mission Impossible: The Beginning Movie",
    "Mission Impossible One Picture",
    "Movie Mission Impossible - 1",
    "Mission Impossible: The Premiere Film",
    "MI One Picture",
    "Mission Impossible 1st Flick",
    "Mission Impossible: The Debut Movie",
    "MI Episode One Movie",
    "Movie - MI 1",
    "Mission Impossible: Part One",
    "Mission Impossible Episode 1 Flick",
    "MI: The Beginning Movie",
    "Mission Impossible 1 Premiere",
    "Movie Mission Impossible: First",
    "Mission Impossible: The Introductory Movie",
    "MI One Premiere",
    "Mission Impossible: The First Picture",
    "Mission Impossible 1st Premiere",
    "Movie Mission: Impossible - 1",
    "MI Episode 1 Flick",
    "Mission Impossible: The Opening Movie",
    "Mission Impossible One Premiere",
    "Mission Impossible: First Episode",
    "MI: The Premiere Movie",
    "Mission Impossible 1st Episode",
    "Movie MI: 1",
    "Mission Impossible",
    "Mission Impossible: The Commencement Movie",
    "Mission Impossible One Opening",
    "MI: Episode 1",
    "Movie - MI Episode 1",
    "Mission Impossible: The First Episode",
    "Mission Impossible One Commencement",
    "MI Episode 1 Premiere",
    "Movie Mission Impossible: Episode 1",
    "Mission Impossible: The First Installment",
    "Mission Impossible One Commencement Movie",
    "MI 1 Commencement",
    "Movie MI: Episode One",
    "Mission Impossible: The First Part",
    "Mission Impossible One Beginning",
    "MI Episode One Premiere",
    "Movie Mission Impossible: The First",
    "Mission Impossible: First Commencement",
    "Mission Impossible One Commencement Flick",
    "MI: Episode 1 Movie",
    "Movie - MI Episode One",
    "Mission Impossible: The Initial Episode",
    "Mission Impossible One Commencement Film",
    "MI 1 Commencement Movie",
    "Movie MI: Episode 1",
    "Mission Impossible: The First Part Movie",
    "Mission Impossible One Beginning Film",
    "MI Episode One Commencement",
    "Movie Mission Impossible: The Premiere",
    "Mission Impossible: First Commencement Movie",
    "Mission Impossible One Commencement Picture",
    "MI: Episode One Premiere",
    "Movie - Mission Impossible One"
]
string2 = "Mission impossible"

# RESULT ANALYSIS
# if similarity > 5.0:different
similarity_arr = []
greatest_similarity = 0
for i in range(len(string1)):
    similarity, dissimilarity = ncd(string1[i], string2)
    similarity_arr.append(similarity)
    if similarity > greatest_similarity:
        greatest_similarity = similarity
for i in range(len(string1)):
    if similarity_arr[i] == greatest_similarity:
        # PRINT WITH SOME COOL-UI
        print(("+"+"-"*len(f"Similarity between '{string1[i]}' and '{string2}': {similarity_arr[i]:.4f} ")+"+"))
        print(f"!\033[1;32mSimilarity between '{string1[i]}' and '{string2}': {similarity_arr[i]:.4f}\033[0m","|")
        print(("+"+"-"*len(f"Similarity between '{string1[i]}' and '{string2}': {similarity_arr[i]:.4f} ")+"+"))
    else:
        print(f"Similarity between '{string1[i]}' and '{string2}': {similarity_arr[i]:.4f}")

end_time = time.time()

elapsed_time = end_time - start_time
print(f"Time elapsed: {elapsed_time} seconds")
